### ISSUE TITLE
Add project to overconstrained.io

### ISSUE THREAD

**Issue by alexbirkett** [Tw1ddle/haxe-kiwi#1]
I'm not sure if you are aware of [overconstrained.io](http://overconstrained.io/)? This project would be a good candidate to be added to the list of cassowary related projects.

Pull requests can be sent [here](https://github.com/hfossli/Overconstrained)

**Comment by Tw1ddle** [comment]
Thanks for the encouragement, sent a pull request just now :+1:

**Comment by Tw1ddle** [comment]
Done :smile:
